In [ ]:
#if outlier data is present then median else mean(i.e. avg)
# for month type data where median and mean fails we use mode
# we fill the null values with mean , median and mode

In [ ]:
################################## LIST COMPREHENSION #######################
# used to comprehend for loops
list_of = [1,2,3,4]
k = []
for i in list_of:
  k.append(i**2)
print(k)

[1, 4, 9, 16]


In [ ]:
#list comprehension  syntax
k = [i**2 for i in list_of if i%2==0 ]
print("The even no. sqaure is :",k)

The even no. sqaure is : [4, 16]


In [ ]:
# if two condn write them before for loop amd for single condn after for loop
k = [i**2 if i%2==0 else i**3  for i in list_of ]
print(k)

[1, 4, 27, 16]


In [ ]:
# set comprehension
k = {i**2 for i in list_of if i%2==0 }
print(k)

{16, 4}


In [ ]:
hq = "It ceases to exist."
k = { i[0] for i in hq.split() }
print(k)

{'I', 'e', 't', 'c'}


In [ ]:
############ FUNCTIONS #################
n = 10
fact = 1
for i in range(1,n+1):
  fact = fact*i
print(fact)

3628800


In [ ]:
#def
"""
def function(arg1 , arg2, ....):
 code
return value
"""
def f(n):
  f = 1
  for i in range(1,n+1):
    f = f*i
  return f
f(10)

3628800

In [ ]:
sample_date = '2020-07-01'
a = sample_date.split('-')
print(a[1])

07


In [ ]:
def quarter(str):
  str=str.split("-")
  month=int(str[1])
  if month<4:
    print("First quarter")
  elif month<7:
    print("Second quarter")
  elif month<10:
    print("Third quarter")
  else:
    print("Fourth quarter")

quarter("12-3-2024")

First quarter


In [ ]:
a = [1,2,3,4,5,6]
value = 100
index = 3
a = a[:3] + [value] + a[3:6]
print(a)
#M2
"""
for i in range(len(a)-1,index-1,-1):
  a[i] = a[i-1]
  a[3] = 100

print(a) """

[1, 2, 3, 100, 4, 5, 6]


In [ ]:
a = [1,2,3,4,5,6]
value = 100
index = 3
# create another list by extend() for last element as last element will not occur after putting 100
def f():
  b = [0]
  a.extend(b)
for i in range(len(a)-1,index-1,-1):
  a[i] = a[i-1]
a[3] = 100

f()

print(a)


[1, 2, 3, 100, 4, 5, 0]


In [ ]:
##################  CLASS #################
class bpit:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def student_name(self):
    print(f"this is class bpit & student name is :{self.name}")

  def student_age(self):
       print(f"this is class bpit & age is :{self.age}")

obj = bpit("name",20)
obj.student_age()
obj.student_name()

this is class bpit & age is :20
this is class bpit & student name is :name


In [ ]:
### METHOD ###
def area(r):
  return 3.14*r*r

In [ ]:
area(3)

28.259999999999998

In [1]:
# exception handling
a = "rahul"
try:
  print(abc)
except:
  print("hello")


hello


In [3]:
#########################  NumPy ################################
#adv :- quicker/more mathematical fns i.e. more functionality
#reduced time comp
#reduced space complexicity   ######   np is alias
import numpy as np

In [12]:
a = np.array([1,2,3,4])
#type(a)
a.shape           #shape(columns,) for 1 d

(4,)

In [5]:
print(a)        # no commas in bw in arrays unlike lists

[1 2 3 4]


TypeError: 'tuple' object is not callable

In [15]:
a = np.array([[1,2,5],[3,4,7]])  # 2 d

print(a)
a. shape       # for 2-d use : shape(rows,cols)

[[1 2 5]
 [3 4 7]]


(2, 3)

In [9]:
a = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])  # 3 d
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
a.shape      #shape(sub array,rows,columns)   for 3_d

(2, 2, 2)

In [16]:
# ndim
a = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(a.ndim)

3


In [17]:
# size (shape to get multiplied)
a = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(a.ndim)
print(a.size)

3
8


In [18]:
#  ndarray.dtype
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [19]:
a = np.array([1.0,2,3,4])
print(a.dtype)

float64


In [21]:
a = np.array(["sdx4",'12'])  # biggest one size
print(a.dtype)

<U4


In [23]:
# ndarray.astype
a = np.array([1,2,3,4])
a.astype('float64')

array([1., 2., 3., 4.])

In [26]:
a = np.array([1,2,3,4])
a.astype('<U5')

array(['1', '2', '3', '4'], dtype='<U5')

In [29]:
a = np.zeros( (3,4),dtype = 'int64')
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:
a = np.ones( (3,4),dtype = 'int64')
print(a+1)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [34]:
# array for random fn
a = np.random.randint(10,15,(2,3,4))
print(a)

[[[11 11 10 12]
  [10 12 13 10]
  [13 13 10 12]]

 [[12 12 10 12]
  [12 11 14 14]
  [14 14 12 12]]]


In [ ]:
# slicing 1-d arry
# a['cols']


#2-d
#a[rows,cols]

#3-d
#a[sub array, rows, cols]


In [36]:
a = np.random.randint(10,15,(3,4))
print(a)

[[11 12 11 14]
 [14 11 13 11]
 [11 13 12 14]]


In [38]:
print(a[1,6])

IndexError: index 6 is out of bounds for axis 1 with size 4

In [39]:
a = np.random.randint(10,15,(2,3,4))
print(a)

[[[10 12 13 11]
  [13 14 11 10]
  [13 10 11 14]]

 [[12 12 14 10]
  [11 12 13 12]
  [13 10 14 11]]]


In [41]:
print(a[1,-2,-3])

12


In [42]:
print(a.T)    # transpose

[[[10 12]
  [13 11]
  [13 13]]

 [[12 12]
  [14 12]
  [10 10]]

 [[13 14]
  [11 13]
  [11 14]]

 [[11 10]
  [10 12]
  [14 11]]]


In [43]:
# np.reshape
# condn : no. of eklements sholud be same
a = np.random.randint(10,15,(4,3))
print(a)

[[14 10 11]
 [14 12 10]
 [12 14 12]
 [11 13 14]]


In [45]:
print(np.reshape(a,(3,4)))

[[14 10 11 14]
 [12 10 12 14]
 [12 11 13 14]]


In [46]:
print(np.reshape(a,(3,2,2)))

[[[14 10]
  [11 14]]

 [[12 10]
  [12 14]]

 [[12 11]
  [13 14]]]


In [49]:
# resize : it has no restriction unlike reshape
# repeats value once values are complete once
print(np.resize(a,(3,2,6)))

[[[14 10 11 14 12 10]
  [12 14 12 11 13 14]]

 [[14 10 11 14 12 10]
  [12 14 12 11 13 14]]

 [[14 10 11 14 12 10]
  [12 14 12 11 13 14]]]


In [50]:
# np.flatten()
# returns alls others arrays to flattened 1-d array

print(a)

[[14 10 11]
 [14 12 10]
 [12 14 12]
 [11 13 14]]


In [51]:
a.flatten()

array([14, 10, 11, 14, 12, 10, 12, 14, 12, 11, 13, 14])

In [ ]:
# copy and view
#shallow and deep copy

In [55]:
'''parse_code("John000Doe000123") -> {
    'F_name': 'John',
    "l_name": 'Doe',
    'id': '123'
}'''

#def f():
s = "John000Doe000123"
a = s.replace('0',' ')
a = a.split()
print(a)


['John', 'Doe', '123']


In [56]:
parse_code = "John000Doe0000123"
def func(parse_code):
  a = parse_code.replace("0", " ")
  a = a.split()
  print(a)
  b = {}
  b["f_name"] = a[0]
  b["l_name"] = a[1]
  b["id"] = a[2]
  print(b)


func(parse_code)

['John', 'Doe', '123']
{'f_name': 'John', 'l_name': 'Doe', 'id': '123'}


In [58]:
########  NumPy ops ##########

a = np.random.randint(10,15,(4,3))
b = np.random.randint(10,20,(4,3))
print(a+b)

[[24 25 22]
 [26 26 22]
 [26 24 29]
 [24 24 25]]


In [59]:
print(a-b)

[[ 2  1  0]
 [ 0  0  2]
 [-2  4 -7]
 [-2  0  3]]


In [60]:
print(a*b)

[[143 156 121]
 [169 169 120]
 [168 140 198]
 [143 144 154]]


In [61]:
a = np.random.randint(10,15,(4,3))
print(a)
print(f"min vlaue in array is :{a.min()}")

[[13 11 13]
 [10 14 13]
 [12 10 12]
 [13 14 13]]
min vlaue in array is :10


In [62]:
a = np.random.randint(10,15,(4,3))
print(a)
print(f"min vlaue in array is :{a.mean()}")

[[10 13 14]
 [11 10 14]
 [14 13 13]
 [10 11 11]]
min vlaue in array is :12.0


In [ ]:
# anagrams : delete the extra elements to make the array same (order is not important)

In [ ]:
a = 'cde'
b = 'dcf'

delete = 'ef'
updated_a = 'cd'
updated_b = 'dc'

In [ ]:
a = 'gfrregewrf'
b = 'fsasagrg'

delete = 'reewrfsasa'
updated_a = 'gfrg'
updated_b = ''

In [86]:
a = (list('cde'))
b = (list('dcf'))
delete = []
u_a = []
u_b = []

for i in a:
  for i in b:
    if (a[0:len(i)-1]==b[0:len(i)-1]):
      a.pop(i)
      b.pop(i)

    else:
      delete.append(i)
      delete.append(i)
print(u_a)
print(u_b)
print(delete)

TypeError: 'str' object cannot be interpreted as an integer